services:
  postgres:
    image: postgres:15-alpine
    container_name: wb-tech
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qqq
      POSGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
      POSGTRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

  # kafka1:
  #   image: bitnami/kafka:4.0.0
  #   container_name: kafka1
  #   ports:
  #     - "29092:29092"
  #   environment:
  #     KAFKA_CFG_NODE_ID: 1
  #     KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  #     KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,CLIENT://:29092"
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT"
  #     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092,CLIENT://localhost:29092"
  #     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
  #     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  #     KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
  #     KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: false
  #     KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: false
  #     KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: true # Корректное завершение работы
  #     KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3 # 3 реплики
  #     KAFKA_CFG_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 86400
  #     KAFKA_CFG_MIN_INSYNC_REPLICAS: 2

  # kafka2:
  #   image: bitnami/kafka:4.0.0
  #   container_name: kafka2
  #   ports:
  #     - "29094:29092"
  #   environment:
  #     KAFKA_CFG_NODE_ID: 2
  #     KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  #     KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,CLIENT://:29092"
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT"
  #     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092,CLIENT://localhost:29092"
  #     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
  #     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  #     KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
  #     KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: false
  #     KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: false
  #     KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: true # Корректное завершение работы
  #     KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3 # 3 реплики
  #     KAFKA_CFG_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 86400
  #     KAFKA_CFG_MIN_INSYNC_REPLICAS: 2

  #   depends_on:
  #     - kafka1

  # kafka3:
  #   image: bitnami/kafka:4.0.0
  #   container_name: kafka3
  #   ports:
  #     - "29096:29092"
  #   environment:
  #     KAFKA_CFG_NODE_ID: 3
  #     KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  #     KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,CLIENT://:29092"
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT"
  #     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9092,CLIENT://localhost:29092"
  #     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
  #     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  #     KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
  #     KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: false
  #     KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLE: false
  #     KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: true # Корректное завершение работы
  #     KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3 # 3 реплики
  #     KAFKA_CFG_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 86400
  #     KAFKA_CFG_MIN_INSYNC_REPLICAS: 2

  #   depends_on:
  #     - kafka2

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    environment:
      - MAXMEMORY=100MB
      - MAXMEMORY_POLICY=volatile-ttl

volumes:
  postgres_data:
