services:
  postgres:
    image: postgres:15-alpine
    container_name: wb-tech
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: qqq
      POSGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
      POSGTRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy

  # kafka:
  #   image: bitnami/kafka:4.0.0
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_CFG_NODE_ID: 1
  #     KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  #     KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  #     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
  #     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
  #     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

  kafka1:
    image: bitnami/kafka:4.0.0
    container_name: kafka1
    ports:
      - "9092:9092"

    environment:
      KAFKA_CFG_NODE_ID: 1

      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9090,EXTERNAL://localhost:9092"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9091,2@kafka2:9091,3@kafka3:9091,4@kafka4:9091"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_GROUP_COORDINATOR_REBALANCE_PROTOCOL: "classic"

      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "2"

  kafka2:
    image: bitnami/kafka:4.0.0
    container_name: kafka2
    ports:
      - "9094:9094"

    environment:
      KAFKA_CFG_NODE_ID: 2

      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9090,EXTERNAL://localhost:9094"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9091,2@kafka2:9091,3@kafka3:9091,4@kafka4:9091"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_GROUP_COORDINATOR_REBALANCE_PROTOCOL: "classic"

      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "2"

  kafka3:
    image: bitnami/kafka:4.0.0
    container_name: kafka3
    ports:
      - "9096:9096"

    environment:
      KAFKA_CFG_NODE_ID: 3

      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9090,EXTERNAL://localhost:9096"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9091,2@kafka2:9091,3@kafka3:9091,4@kafka4:9091"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_GROUP_COORDINATOR_REBALANCE_PROTOCOL: "classic"

      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "2"

  kafka4:
    image: bitnami/kafka:4.0.0
    container_name: kafka4
    ports:
      - "9098:9098"

    environment:
      KAFKA_CFG_NODE_ID: 4

      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9098"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka4:9090,EXTERNAL://localhost:9098"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9091,2@kafka2:9091,3@kafka3:9091,4@kafka4:9091"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CLUSTER_ID: "WmXw6nQkSq6Z5xL1pPDTEg"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_GROUP_COORDINATOR_REBALANCE_PROTOCOL: "classic"

      KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE: "true"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "2"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    environment:
      - MAXMEMORY=100MB
      - MAXMEMORY_POLICY=volatile-ttl

volumes:
  postgres_data:
