CREATE DATABASE mydb;
\connect mydb

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: delivery_info; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.delivery_info (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(100) NOT NULL,
    zip character varying(100) NOT NULL,
    city character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    region character varying(255) NOT NULL,
    email character varying(255) NOT NULL
);


ALTER TABLE public.delivery_info OWNER TO dev;

--
-- Name: delivery_info_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.delivery_info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.delivery_info_id_seq OWNER TO dev;

--
-- Name: delivery_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.delivery_info_id_seq OWNED BY public.delivery_info.id;


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO dev;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.items (
    chrt_id integer NOT NULL,
    track_number text NOT NULL,
    price numeric(12,2) NOT NULL,
    rid text NOT NULL,
    name character varying(255) NOT NULL,
    sale smallint NOT NULL,
    size character varying(10) NOT NULL,
    total_price numeric(12,2) NOT NULL,
    nm_id bigint NOT NULL,
    brand character varying(255) NOT NULL,
    status smallint NOT NULL
);


ALTER TABLE public.items OWNER TO dev;

--
-- Name: items_chrt_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.items_chrt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.items_chrt_id_seq OWNER TO dev;

--
-- Name: items_chrt_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.items_chrt_id_seq OWNED BY public.items.chrt_id;


--
-- Name: orders; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    order_uid text NOT NULL,
    track_number text NOT NULL,
    entry character varying(255) NOT NULL,
    delivery_id bigint NOT NULL,
    payment_id bigint NOT NULL,
    locale character varying(10) NOT NULL,
    internal_signature text NOT NULL,
    customer_id text NOT NULL,
    delivery_service character varying(255) NOT NULL,
    shardkey text NOT NULL,
    sm_id smallint NOT NULL,
    date_created timestamp with time zone DEFAULT now(),
    oof_shard text NOT NULL
);


ALTER TABLE public.orders OWNER TO dev;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.orders_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.orders_id_seq OWNER TO dev;

--
-- Name: orders_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.orders_id_seq OWNED BY public.orders.id;


--
-- Name: orders_items; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.orders_items (
    id integer NOT NULL,
    order_id bigint NOT NULL,
    item_id bigint NOT NULL
);


ALTER TABLE public.orders_items OWNER TO dev;

--
-- Name: orders_items_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.orders_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.orders_items_id_seq OWNER TO dev;

--
-- Name: orders_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.orders_items_id_seq OWNED BY public.orders_items.id;


--
-- Name: payment_info; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.payment_info (
    id integer NOT NULL,
    transaction character varying(255) NOT NULL,
    request_id text NOT NULL,
    currency character varying(20) NOT NULL,
    provider character varying(255) NOT NULL,
    amount numeric(12,2) NOT NULL,
    payment_dt bigint NOT NULL,
    bank character varying(255) NOT NULL,
    delivery_cost numeric(12,2) NOT NULL,
    goods_total numeric(12,2) NOT NULL,
    custom_fee numeric(12,2) NOT NULL
);


ALTER TABLE public.payment_info OWNER TO dev;

--
-- Name: payment_info_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

CREATE SEQUENCE public.payment_info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.payment_info_id_seq OWNER TO dev;

--
-- Name: payment_info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: dev
--

ALTER SEQUENCE public.payment_info_id_seq OWNED BY public.payment_info.id;


--
-- Name: delivery_info id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.delivery_info ALTER COLUMN id SET DEFAULT nextval('public.delivery_info_id_seq'::regclass);


--
-- Name: items chrt_id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.items ALTER COLUMN chrt_id SET DEFAULT nextval('public.items_chrt_id_seq'::regclass);


--
-- Name: orders id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders ALTER COLUMN id SET DEFAULT nextval('public.orders_id_seq'::regclass);


--
-- Name: orders_items id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders_items ALTER COLUMN id SET DEFAULT nextval('public.orders_items_id_seq'::regclass);


--
-- Name: payment_info id; Type: DEFAULT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.payment_info ALTER COLUMN id SET DEFAULT nextval('public.payment_info_id_seq'::regclass);


--
-- Data for Name: delivery_info; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.delivery_info (id, name, phone, zip, city, address, region, email) FROM stdin;
17	Test Testov	+9720000000	2639809	Kiryat Mozkin	Ploshad Mira 15	Kraiot	test@gmail.com
\.


--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2025-08-05 17:50:30.67404
18	20250805174347	t	2025-08-06 11:17:20.51764
19	20250805175343	t	2025-08-06 11:17:20.528085
20	20250805181022	t	2025-08-06 11:17:20.533296
23	20250805181423	t	2025-08-06 12:48:23.954766
25	20250805182806	t	2025-08-06 12:59:20.458239
\.


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.items (chrt_id, track_number, price, rid, name, sale, size, total_price, nm_id, brand, status) FROM stdin;
9934930	WBILMTESTTRACK	453.00	ab4219087a764ae0btest	Mascaras	30	0	317.00	2389212	Vivienne Sabo	202
1	WBILMTESTTRACK	453.00	ab4219087a764ae0btest	Mascaras	30	43	317.00	2389212	Vivienne Sabo	202
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.orders (id, order_uid, track_number, entry, delivery_id, payment_id, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard) FROM stdin;
9	b563feb7b2b84b6test	WBILMTESTTRACK	WBIL	17	14	en		test	meest	9	99	2021-11-26 06:22:19+00	1
\.


--
-- Data for Name: orders_items; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.orders_items (id, order_id, item_id) FROM stdin;
1	9	9934930
2	9	9934930
3	9	1
\.


--
-- Data for Name: payment_info; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.payment_info (id, transaction, request_id, currency, provider, amount, payment_dt, bank, delivery_cost, goods_total, custom_fee) FROM stdin;
14	b563feb7b2b84b6test		USD	wbpay	1817.00	1637907727	alpha	1500.00	317.00	0.00
\.


--
-- Name: delivery_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.delivery_info_id_seq', 17, true);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 25, true);


--
-- Name: items_chrt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.items_chrt_id_seq', 1, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.orders_id_seq', 9, true);


--
-- Name: orders_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.orders_items_id_seq', 3, true);


--
-- Name: payment_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.payment_info_id_seq', 14, true);


--
-- Name: delivery_info delivery_info_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.delivery_info
    ADD CONSTRAINT delivery_info_pkey PRIMARY KEY (id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (chrt_id);


--
-- Name: orders_items orders_items_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders_items
    ADD CONSTRAINT orders_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payment_info payment_info_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.payment_info
    ADD CONSTRAINT payment_info_pkey PRIMARY KEY (id);


--
-- Name: orders orders_delivery_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.delivery_info(id) ON DELETE CASCADE;


--
-- Name: orders_items orders_items_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders_items
    ADD CONSTRAINT orders_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(chrt_id) ON DELETE CASCADE;


--
-- Name: orders_items orders_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders_items
    ADD CONSTRAINT orders_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: orders orders_payment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payment_info(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

